### ISSUE TITLE
Do you know how to configure IntelliJ to compile this project successfully?

### ISSUE THREAD

**Issue by seglo** [konvergeio/cofoja-example#1]
I've been trying to get a cofoja project compiling in IntelliJ with little success.  I have the same problems when importing this project.

```
Error:java: error in contract: package com.google.java.contract.core.agent does not exist
Error:java: error in contract: package com.google.java.contract does not exist
```
Have you ever used cofoja with IntelliJ?

**Comment by nkavian** [comment]
I'm not a fan of IntelliJ :)  Regardless, the issue lays in the cofoja library and hoping Nhat can fix it.  If that happens, I'll release a new mavenized version.

I think this error you saw was a result of changing the example pom I provided to remove the Java Agent statements.  At least that's how I reproduced it.  Let's track the issue with this ticket you opened: https://github.com/nhatminhle/cofoja/issues/45
